import re

def translate_index():
    with open('index.html', 'r', encoding='utf-8') as f:
        content = f.read()

    replacements = {
        'lang="id"': 'lang="vi"',
        'Website Undangan Pernikahan Wahyu dan Riski Secara Online': 'Website Thiệp Cưới Trực Tuyến Của Wahyu và Riski',
        'undangan, wedding, undangan digital, undangan online, wedding invitation, template undangan, template undangan pernikahan, undangan pernikahan, template undangan online, wedding invitation github, template website, template website undangan pernikahan': 'thiệp cưới, đám cưới, thiệp cưới kỹ thuật số, thiệp cưới trực tuyến, thiệp mời, mẫu thiệp cưới, mẫu thiệp cưới trực tuyến, thiệp cưới github, mẫu website thiệp cưới',
        'Jika tidak menggunakan komentar, hapus atribut data-key dan data-url, serta abaikan file dashboard.html.': 'Nếu bạn không sử dụng bình luận, hãy xóa các thuộc tính data-key và data-url, và bỏ qua file dashboard.html.',
        'Jika tidak menggunakan lagu, hapus atribut data-audio.': 'Nếu bạn không sử dụng nhạc, hãy xóa thuộc tính data-audio.',
        'Ubah atribut time menjadi time-data (mengikuti format yang ditentukan).': 'Thay đổi thuộc tính time thành time-data (theo định dạng yêu cầu).',
        "Atur data-confetti ke 'false' jika tidak ingin menggunakan konfeti. Hanya berfungsi saat komentar dimatikan.": "Thiết lập data-confetti thành 'false' nếu bạn không muốn sử dụng pháo giấy. Chỉ hoạt động khi bình luận bị tắt.",
        'Kamu bisa langsung gunakan file rilis GitHub (guest.css, guest.js, admin.css, admin.js) tanpa perlu build.': 'Bạn có thể trực tiếp sử dụng các file phát hành trên GitHub (guest.css, guest.js, admin.css, admin.js) mà không cần build.',
        "Disarankan menggunakan 'data-src' pada tag <img>": "Nên sử dụng 'data-src' trên thẻ <img>",
        'Rabu, 15 Maret 2023': 'Thứ Tư, 15 Tháng 3 Năm 2023',
        'Undangan Pernikahan': 'Thiệp Cưới',
        'Save Google Calendar': 'Lưu Lịch Google',
        'Scroll Down': 'Cuộn Xuống',
        'Tanpa mengurangi rasa hormat, kami mengundang Anda untuk berkenan menghadiri acara pernikahan kami:': 'Với tất cả sự tôn trọng, chúng tôi kính mời quý vị đến tham dự lễ cưới của chúng tôi:',
        'Putra ke-1': 'Con trai thứ nhất',
        'Bapak lorem ipsum': 'Ông lorem ipsum',
        '>dan<': '>và<',
        'Ibu lorem ipsum': 'Bà lorem ipsum',
        'Putri ke-2': 'Con gái thứ 2',
        "Allah Subhanahu Wa Ta'ala berfirman": "Allah Subhanahu Wa Ta'ala đã phán",
        'Dan segala sesuatu Kami ciptakan berpasang-pasangan agar kamu mengingat (kebesaran Allah).': 'Và mọi thứ Chúng Ta tạo ra thành từng cặp để các người ghi nhớ (sự vĩ đại của Allah).',
        'dan sesungguhnya Dialah yang menciptakan pasangan laki-laki dan perempuan,': 'và quả thật, Ngài là đấng tạo ra cặp đôi nam và nữ,',
        'Kisah Cinta': 'Câu chuyện tình yêu',
        'Jika tidak ingin menggunakan video, hapus seluruh tag dengan id="video-love-story" di bawah ini.': 'Nếu không muốn sử dụng video, hãy xóa toàn bộ thẻ có id="video-love-story" bên dưới.',
        'Lihat Story': 'Xem Câu Chuyện',
        'Awal Pertemuan Sederhana': 'Cuộc Gặp Gỡ Đơn Giản Đầu Tiên',
        'Pada Januari 2025, Wahyu, seorang desainer grafis berusia 28 tahun, bertemu Riski, copywriter yang dikenal cerdas dan pendiam, dalam proyek branding perusahaan. Interaksi mereka di ruang rapat terbatas pada urusan kerja, penuh adab dan profesional. Tanpa Wahyu ketahui, Riski sebenarnya pernah melihat karya desain Wahyu di lomba nasional dua tahun lalu dan kagum dengan bakatnya. Namun, sesuai prinsipnya, Riski menjaga jarak dan hanya fokus pada tugas, menghindari interaksi yang tidak perlu.': 'Vào tháng 1 năm 2025, Wahyu, một nhà thiết kế đồ họa 28 tuổi, gặp Riski, một người viết quảng cáo thông minh và ít nói, trong một dự án thương hiệu của công ty. Sự tương tác của họ trong phòng họp chỉ giới hạn trong công việc, đầy lịch sự và chuyên nghiệp. Wahyu không biết rằng, Riski thực sự đã từng thấy tác phẩm thiết kế của Wahyu tại một cuộc thi quốc gia hai năm trước và rất ngưỡng mộ tài năng của anh. Tuy nhiên, theo nguyên tắc của mình, Riski giữ khoảng cách và chỉ tập trung vào nhiệm vụ, tránh những tương tác không cần thiết.',
        'Benih Cinta dalam Ujian': 'Hạt Giống Tình Yêu Trong Thử Thách',
        'Memasuki Februari 2025, proyek mereka menghadapi krisis: klien menolak konsep awal dan mengancam membatalkan kontrak. Di tengah tekanan, Riski tampil dengan solusi kreatif yang menyelamatkan proyek, membuat Wahyu terkesan dengan ketenangan dan kecerdasannya. Diam-diam, Wahyu mulai memperhatikan Riski lebih dalam, terutama melalui unggahan media sosialnya yang penuh dengan nilai keimanan dan kesabaran. Merasa ada kesamaan visi, Wahyu beristikharah dan memutuskan memulai taaruf. Ia menghubungi seorang ustaz terpercaya sebagai perantara. Kejutan muncul saat Riski mengaku bahwa ia juga telah lama memperhatikan Wahyu, namun menahan diri hingga ada niat yang jelas, sebuah pengakuan yang membuat hati Wahyu hangat.': 'Bước vào tháng 2 năm 2025, dự án của họ phải đối mặt với một cuộc khủng hoảng: khách hàng từ chối ý tưởng ban đầu và đe dọa hủy bỏ hợp đồng. Giữa lúc áp lực, Riski đã đưa ra một giải pháp sáng tạo cứu vãn dự án, khiến Wahyu ấn tượng bởi sự bình tĩnh và trí thông minh của cô. Âm thầm, Wahyu bắt đầu chú ý đến Riski nhiều hơn, đặc biệt là qua các bài đăng trên mạng xã hội chứa đầy giá trị đức tin và sự kiên nhẫn. Cảm thấy có chung tầm nhìn, Wahyu đã cầu nguyện (istikharah) và quyết định bắt đầu tìm hiểu (taaruf). Anh liên lạc với một giáo sĩ đáng tin cậy để làm trung gian. Điều bất ngờ là Riski thú nhận cô cũng đã để ý đến Wahyu từ lâu nhưng kìm nén cho đến khi có ý định rõ ràng, một lời thú nhận khiến trái tim Wahyu ấm áp.',
        'Langkah Menuju Ridha Allah': 'Bước Tới Sự Hài Lòng Của Allah',
        'Proses taaruf berjalan penuh keikhlasan, dengan pendamping yang memastikan setiap langkah sesuai syariat. Wahyu dan Riski saling terbuka tentang impian membangun keluarga yang diridhai Allah. Namun, sebuah ujian datang: keluarga Riski ragu karena latar belakang ekonomi Wahyu yang sederhana. Di sinilah plot twist terungkap—Wahyu mempresentasikan rencana usaha sosial berbasis seni yang telah ia kembangkan diam-diam, menunjukkan visinya untuk memberi manfaat bagi umat. Presentasi itu meluluhkan hati keluarga Riski. Pada Maret 2025, setelah istikharah dan mendapat restu keluarga, Wahyu melamar Riski dalam acara sederhana namun penuh makna. Dengan niat tulus, mereka melangkah menuju pernikahan, yakin bahwa Allah telah merajut kisah mereka dengan indah.': 'Quá trình tìm hiểu diễn ra với đầy sự chân thành, với người đồng hành đảm bảo mỗi bước đều tuân thủ luật Hồi giáo. Wahyu và Riski cởi mở với nhau về ước mơ xây dựng một gia đình được Allah hài lòng. Tuy nhiên, một thử thách ập đến: gia đình Riski do dự vì hoàn cảnh kinh tế giản dị của Wahyu. Đây là lúc bước ngoặt xuất hiện—Wahyu trình bày về một kế hoạch kinh doanh xã hội dựa trên nghệ thuật mà anh âm thầm phát triển, thể hiện tầm nhìn mang lại lợi ích cho cộng đồng. Bài thuyết trình đã làm tan chảy trái tim gia đình Riski. Vào tháng 3 năm 2025, sau khi cầu nguyện (istikharah) và nhận được sự chúc phúc của gia đình, Wahyu cầu hôn Riski trong một buổi lễ giản dị nhưng đầy ý nghĩa. Với ý định chân thành, họ bước tới hôn nhân, tin chắc rằng Allah đã dệt nên câu chuyện của họ một cách tuyệt đẹp.',
        'Moment Bahagia': 'Khoảnh Khắc Hạnh Phúc',
        '>Hari<': '>Ngày<',
        '>Jam<': '>Giờ<',
        '>Menit<': '>Phút<',
        '>Detik<': '>Giây<',
        "Dengan memohon rahmat dan ridho Allah Subhanahu Wa Ta'ala, insyaAllah kami akan menyelenggarakan acara:": "Cầu xin sự thương xót và hài lòng của Allah Subhanahu Wa Ta'ala, nếu Allah muốn, chúng tôi sẽ tổ chức sự kiện:",
        'Akad': 'Lễ Thành Hôn (Akad)',
        'Pukul 10.00 WIB - Selesai': '10:00 WIB - Kết thúc',
        'Resepsi': 'Tiệc Cưới',
        'Pukul 13.00 WIB - Selesai': '13:00 WIB - Kết thúc',
        'Demi kehangatan bersama, kami memohon kesediaan Anda untuk mengenakan dress code berikut:': 'Vì sự ấm áp chung, chúng tôi kính mong quý vị mặc trang phục theo quy định (dress code) sau đây:',
        'Busana batik dan bersepatu.': 'Trang phục trang trọng và mang giày.',
        'Lihat Google Maps': 'Xem Google Maps',
        'Galeri': 'Thư Viện Ảnh',
        'Love Gift': 'Quà Tặng Tình Yêu',
        'Dengan hormat, bagi Anda yang ingin memberikan tanda kasih kepada kami, dapat melalui:': 'Trân trọng, đối với những quý vị muốn trao tặng món quà yêu thương cho chúng tôi, quý vị có thể thực hiện thông qua:',
        'Transfer': 'Chuyển Khoản',
        '>Info<': '>Thông Tin<',
        'Bank Central Asia': 'Ngân hàng Central Asia',
        'Ubah juga data-copy sesuai dengan no rekening': 'Hãy thay đổi cả data-copy theo số tài khoản',
        'Qris': 'QRIS',
        '>Gift<': '>Quà Tặng<',
        'Ubah juga data-copy sesuai dengan no hp': 'Hãy thay đổi cả data-copy theo số điện thoại',
        'Ubah juga data-copy sesuai dengan alamat': 'Hãy thay đổi cả data-copy theo địa chỉ',
        'Ucapan &amp; Doa': 'Lời Chúc &amp; Lời Cầu Nguyện',
        '>Nama<': '>Tên<',
        'Isikan Nama Anda': 'Nhập tên của bạn',
        '>Presensi<': '>Sự Hiện Diện<',
        'Konfirmasi Presensi': 'Xác nhận sự hiện diện',
        '&#9989; Datang': '&#9989; Sẽ đến',
        '&#10060; Berhalangan': '&#10060; Không thể đến',
        'Bestieee!!!': 'Bạn thân mến!!!',
        'Cobain like seperti Instagram, dengan tap tap bagian komentarnya': 'Hãy thử thả tim giống như Instagram bằng cách chạm chạm vào phần bình luận nhé',
        'Sama bisa format text seperti Whatsapp lohh... cobainn jugaaa, makaciwww bestieee': 'Cũng có thể định dạng văn bản như Whatsapp... hãy thử xem, cảm ơn bạn rất nhiều',
        'Tulis Ucapan dan Doa': 'Viết Lời Chúc và Lời Cầu Nguyện',
        '>Send<': '>Gửi<',
        'Terima kasih atas perhatian dan doa restu Anda, yang menjadi kebahagiaan serta kehormatan besar bagi kami.': 'Cảm ơn sự quan tâm và lời cầu nguyện chúc phúc của quý vị, đó là niềm hạnh phúc và vinh dự lớn lao đối với chúng tôi.',
        'Kepada Yth Bapak/Ibu/Saudara/i': 'Kính gửi Ông/Bà/Anh/Chị/Em',
        'Open Invitation': 'Mở Thiệp',
        '>Home<': '>Trang Chủ<',
        '>Mempelai<': '>Cô Dâu Chú Rể<',
        '>Tanggal<': '>Ngày<',
        '>Ucapan<': '>Lời Chúc<',
        'Booting application...': 'Đang khởi động ứng dụng...',
        'Sorry, this invitation requires javascript to work': 'Xin lỗi, thiệp mời này yêu cầu javascript để hoạt động',
        '>Nama Wahyu Siapa<': '>Wahyu<', # This is likely a placeholder for a name, keeping it as is for now
        '>Nama Riski Siapa<': '>Riski<', # This is likely a placeholder for a name, keeping it as is for now
        # Additional translations for index.html
        'The Wedding Of': 'Đám Cưới Của',
        'Previous': 'Trước',
        'Next': 'Tiếp',
        'Wahyu Siapa?': 'Wahyu là ai?',
        'Riski Siapa?': 'Riski là ai?',
        'Build with': 'Được xây dựng bởi',
        'from': 'từ',
        '<!-- If you don\'t want to use the video, remove the entire tag with id="video-love-story" below. -->': '',
    }

    for k, v in replacements.items():
        content = content.replace(k, v)

    with open('index.html', 'w', encoding='utf-8') as f:
        f.write(content)

def translate_dashboard():
    with open('dashboard.html', 'r', encoding='utf-8') as f:
        content = f.read()

    replacements = {
        'lang="en"': 'lang="vi"',
        'Dashboard Ulems': 'Bảng Điều Khiển Ulems',
        '>Home<': '>Trang Chủ<',
        '>Setting<': '>Cài Đặt<',
        '>Undangan<': '>Thiệp Cưới<',
        '>Logout<': '>Đăng Xuất<',
        '>Download<': '>Tải Xuống<',
        '>Theme<': '>Giao Diện<',
        '>Comments<': '>Bình Luận<',
        '>Present<': '>Sẽ Đến<',
        '>Absent<': '>Không Thể Đến<',
        '>Likes<': '>Lượt Thích<',
        '>Comment<': '>Bình Luận<',
        'Type to comment': 'Nhập bình luận của bạn',
        '>Send<': '>Gửi<',
        '>Email<': '>Email<',
        '>Name<': '>Tên<',
        '>Change<': '>Thay Đổi<',
        '>Access Key<': '>Khóa Truy Cập (Access Key)<',
        'Regenerate key': 'Tạo lại khóa',
        '>Regenerate<': '>Tạo Lại<',
        '>Time Zone<': '>Múi Giờ<',
        '>Tenor Key<': '>Khóa Tenor<',
        'Api key tenor': 'Mã API Tenor',
        '>Save<': '>Lưu<',
        '>Control<': '>Điều Khiển<',
        'Filter bad word': 'Lọc từ ngữ xấu',
        'Confetti animation': 'Hiệu ứng pháo giấy',
        'Can reply': 'Cho phép trả lời',
        'Can edit': 'Cho phép chỉnh sửa',
        'Can delete': 'Cho phép xóa',
        '>Change Password<': '>Đổi Mật Khẩu<',
        'Old Password': 'Mật Khẩu Cũ',
        'New Password': 'Mật Khẩu Mới',
        '>Love Project<': '>Dự Án Yêu Thương<',
        'Discover and support this project on': 'Khám phá và ủng hộ dự án này trên',
        'Enter your email': 'Nhập email của bạn',
        'Enter your password': 'Nhập mật khẩu của bạn',
        '>Password<': '>Mật Khẩu<',
        '>Login<': '>Đăng Nhập<',
        # Các bình luận trong Dashboard
        '<!-- Common -->': '<!-- Chung -->',
        '<!-- Appearance -->': '<!-- Giao Diện -->',
        '<!-- Preconnect CDN -->': '<!-- Kết Nối Sớm CDN -->',
        '<!-- Preload Resources -->': '<!-- Tải Trước Tài Nguyên -->',
        '<!-- Font -->': '<!-- Phông Chữ -->',
        '<!-- Dependencies CSS -->': '<!-- CSS Phụ Thuộc -->',
        '<!-- Dependencies JS -->': '<!-- JS Phụ Thuộc -->',
        '<!-- <html lang="en" data-bs-theme="auto"> [\'auto\', \'dark\', \'light\'] -->': '<!-- <html lang="vi" data-bs-theme="auto"> [\'auto\', \'dark\', \'light\'] -->',
        '<!-- Nav bottom -->': '<!-- Thanh Điều Hướng Dưới Cùng -->',
        '<!-- Main -->': '<!-- Chính -->',
        '<!-- Header -->': '<!-- Tiêu Đề -->',
        '<!-- Body -->': '<!-- Nội Dung -->',
        '<!-- Menu -->': '<!-- Menu -->',
        '<!-- Content -->': '<!-- Nội Dung -->',
        '<!-- Home -->': '<!-- Trang Chủ -->',
        '<!-- Sub Header -->': '<!-- Tiêu Đề Phụ -->',
        '<!-- Stats -->': '<!-- Thống Kê -->',
        '<!-- Form -->': '<!-- Biểu Mẫu -->',
        '<!-- Comments -->': '<!-- Bình Luận -->',
        '<!-- Pagination -->': '<!-- Phân Trang -->',
        '<!-- Setting -->': '<!-- Cài Đặt -->',
        '<!-- Email -->': '<!-- Email -->',
        '<!-- Name -->': '<!-- Tên -->',
        '<!-- Access Key -->': '<!-- Khóa Truy Cập -->',
        '<!-- Time Zone -->': '<!-- Múi Giờ -->',
        '<!-- Tenor Key -->': '<!-- Khóa Tenor -->',
        '<!-- Toggle -->': '<!-- Tùy Chọn -->',
        '<!-- Change Password -->': '<!-- Đổi Mật Khẩu -->',
        '<!-- Logout -->': '<!-- Đăng Xuất -->',
        '<!-- Modal login -->': '<!-- Modal Đăng Nhập -->',
    }

    for k, v in replacements.items():
        content = content.replace(k, v)

    with open('dashboard.html', 'w', encoding='utf-8') as f:
        f.write(content)

translate_index()
translate_dashboard()
print("Done!")
